plugins {
	id 'net.fabricmc.fabric-loom' version "${loom_version}"
	id 'maven-publish'
}

version = project.mod_version
group = project.maven_group

repositories {
	maven {
		url 'https://masa.dy.fi/maven'
	}
	maven {
		url 'https://jitpack.io'
	}
	maven {
		url 'https://www.cursemaven.com'
	}
	maven {
		url = "https://maven.fabricmc.net/"
	}
	maven {
		url = "https://oss.sonatype.org/content/repositories/snapshots"
	}
	maven {
		name = "Modrinth"
		url = "https://api.modrinth.com/maven"
	}
	maven {
		url "https://maven.shedaniel.me"
	}
}

dependencies {
	// To change the versions see the gradle.properties file
	minecraft "com.mojang:minecraft:${project.minecraft_version}"
	implementation "net.fabricmc:fabric-loader:${project.loader_version}"
	// luck perm
	runtimeOnly "maven.modrinth:luckperms:v5.4.133-fabric"

	// carpet
	implementation "carpet:fabric-carpet:${project.carpet_core_version}"

	// Fabric Permission API
	include(implementation('me.lucko:fabric-permissions-api:0.7.0'))

	// Fabric API. This is technically optional, but you probably want it anyway.
	implementation "net.fabricmc.fabric-api:fabric-api:${project.fabric_version}"
}

loom {
	accessWidenerPath = file("src/main/resources/slsa.accesswidener")
}

processResources {
	def modVersion = project.version
	inputs.property "version", modVersion

	filesMatching("fabric.mod.json") {
		expand "version": modVersion
	}
}

tasks.withType(JavaCompile).configureEach {
	// Minecraft 26.1 and upwards uses Java 25.
	it.options.release = 25
}

java {
	// Loom will automatically attach sourcesJar to a RemapSourcesJar task and to the "build" task
	// if it is present.
	// If you remove this line, sources will not be generated.
	withSourcesJar()

	sourceCompatibility = JavaVersion.VERSION_25
	targetCompatibility = JavaVersion.VERSION_25
}

jar {
	def baseName = project.base.archivesName.get()
	from("LICENSE") {
		rename { "${it}_${baseName}"}
	}
}

// configure the maven publication
publishing {
	publications {
		mavenJava(MavenPublication) {
			from components.java
		}
	}

	// See https://docs.gradle.org/current/userguide/publishing_maven.html for information on how to set up publishing.
	repositories {
		// Add repositories to publish to here.
		// Notice: This block does NOT have the same function as the block in the top level.
		// The repositories here will be used for publishing your artifact, not for
		// retrieving dependencies.
	}
}
